version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_ROOT_HOST:"%"
      - MYSQL_USER:$DB_USERNAME
      - MYSQL_PASSWORD:$DB_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD:1
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW databases'"
      interval: 10s
      retries: 3
  app:
    volumes:
    - ".:/rrooms-backend"
    - /rrooms-backend/node_modules
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: ./Dockerfile.development
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 4000:4000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

volumes:
  db:
